language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
- 2.2.7
- 2.3.4
- 2.4.1
branches:
  only:
    - 4.0-stable
before_install:
  - gem install bundler
before_script: bundle exec rake alchemy:spec:prepare
script: bundle exec rspec
after_success: bundle exec codeclimate-test-reporter
env:
  - DB=mysql
  - DB=postgresql
