language: ruby
dist: trusty
sudo: false
cache:
  bundler: true
rvm:
  - 2.5.5
  - 2.6.6
  - 2.7.0
env:
  matrix:
    - ALCHEMY_BRANCH=4.4-stable
    - ALCHEMY_BRANCH=4.5-stable
    - ALCHEMY_BRANCH=4.6-stable
    - ALCHEMY_BRANCH=master
matrix:
  fast_finish: true
  allow_failures:
    - env: ALCHEMY_BRANCH=master
script: bundle exec rake
