language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
branches:
  only:
    - master
before_script: 'bundle exec rake alchemy:spec:prepare'
script: 'bundle exec rspec'
env:
  - DB=mysql
  - DB=postgresql
