language: ruby
dist: bionic
services:
  - mysql
addons:
  postgresql: "10"
sudo: false
cache: bundler
rvm:
  - 2.5.5
  - 2.6.3
branches:
  only:
    - master
before_install:
  - gem install bundler
script: rake
after_success: bundle exec codeclimate-test-reporter
env:
  - DB=mysql
  - DB=postgresql
